name: nvidia-4090-compile

on:
  pull_request:
    branches: [ '*' ]

jobs:
  test:
    runs-on: 'nvidia-4090'
    if: |
      (github.event_name == 'push' && github.ref != 'refs/heads/main' && !startsWith(github.ref, 'refs/pull/')) ||
      (github.event_name == 'pull_request' && github.event.pull_request.base.ref != 'main')
    env:
      COMPILER_MODE: 1
      SKIP_TEST_CHUNK_VARLEN: 1
      CI_ENV: 1
      TRITON_PRINT_AUTOTUNING: 1
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Check GPU status
        run: |
          python scripts/check_gpu.py
          if [ $? -ne 0 ]; then
            echo "GPU is occupied. Stopping the workflow."
            exit 1
          fi

      - name: Setup python
        run: pip install --upgrade pytest setuptools wheel ninja

      - name: Setup fla
        run: pip install --no-use-pep517 .

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v46.0.3

      - name: Find dependent test files
        id: find-dependent-tests
        run: |
          # Run the Python script to find dependent test files
          TEST_FILES=$(python scripts/find_dependent_tests.py "${{ steps.changed-files.outputs.all_changed_files }}")
          echo "test_files=$TEST_FILES" >> $GITHUB_OUTPUT

      - name: Run pytest on dependent test files
        run: |
          if [ -n "${{ steps.find-dependent-tests.outputs.test_files }}" ]; then
            pytest ${{ steps.find-dependent-tests.outputs.test_files }} --capture=no
          else
            echo "No dependent test files to run."
          fi
